# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 673)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.date_time_hide = QtWidgets.QWidget(Form)
        self.date_time_hide.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_time_hide.sizePolicy().hasHeightForWidth())
        self.date_time_hide.setSizePolicy(sizePolicy)
        self.date_time_hide.setObjectName("date_time_hide")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.date_time_hide)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.date_widget_hide = QtWidgets.QLabel(self.date_time_hide)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_widget_hide.setFont(font)
        self.date_widget_hide.setStyleSheet("color: #eaf0ff;\n"
"")
        self.date_widget_hide.setAlignment(QtCore.Qt.AlignCenter)
        self.date_widget_hide.setObjectName("date_widget_hide")
        self.verticalLayout_6.addWidget(self.date_widget_hide)
        self.time_widget_hide = QtWidgets.QLabel(self.date_time_hide)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.time_widget_hide.setFont(font)
        self.time_widget_hide.setStyleSheet("color: #eaf0ff;")
        self.time_widget_hide.setAlignment(QtCore.Qt.AlignCenter)
        self.time_widget_hide.setObjectName("time_widget_hide")
        self.verticalLayout_6.addWidget(self.time_widget_hide)
        self.verticalLayout.addWidget(self.date_time_hide)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.date_widget_hide.setText(_translate("Form", "DATE_HIDE"))
        self.time_widget_hide.setText(_translate("Form", "TIME_HIDE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
