# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(388, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.black_container = QtWidgets.QWidget(Form)
        self.black_container.setStyleSheet("#black_container {\n"
"    background: black;\n"
"}")
        self.black_container.setObjectName("black_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.black_container)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.container = QtWidgets.QWidget(self.black_container)
        self.container.setAutoFillBackground(False)
        self.container.setStyleSheet("#container {\n"
"    border-image: url(:/src/resource/back2.png); \n"
"}")
        self.container.setObjectName("container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.date_widget = QtWidgets.QLabel(self.container)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date_widget.setFont(font)
        self.date_widget.setStyleSheet("color: #161b22;\n"
"")
        self.date_widget.setAlignment(QtCore.Qt.AlignCenter)
        self.date_widget.setObjectName("date_widget")
        self.verticalLayout.addWidget(self.date_widget)
        self.time_widget = QtWidgets.QLabel(self.container)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.time_widget.setFont(font)
        self.time_widget.setStyleSheet("color: #161b22;")
        self.time_widget.setAlignment(QtCore.Qt.AlignCenter)
        self.time_widget.setObjectName("time_widget")
        self.verticalLayout.addWidget(self.time_widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.up_container = QtWidgets.QWidget(self.container)
        self.up_container.setMinimumSize(QtCore.QSize(0, 180))
        self.up_container.setMaximumSize(QtCore.QSize(16777215, 180))
        self.up_container.setObjectName("up_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.up_container)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.options_container = QtWidgets.QWidget(self.up_container)
        self.options_container.setObjectName("options_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.options_container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.options_panel = QtWidgets.QWidget(self.options_container)
        self.options_panel.setMinimumSize(QtCore.QSize(140, 0))
        self.options_panel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.options_panel.setStyleSheet("QWidget {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 128);\n"
"}")
        self.options_panel.setObjectName("options_panel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.options_panel)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.options_panel)
        self.label.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #eaf0ff;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.restart_panel_button = QtWidgets.QPushButton(self.options_panel)
        self.restart_panel_button.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    color: #eaf0ff;\n"
"}\n"
"\n"
"QPushButton[select=\"true\"] {\n"
"    background: #767676;\n"
"}")
        self.restart_panel_button.setObjectName("restart_panel_button")
        self.verticalLayout_3.addWidget(self.restart_panel_button)
        self.poweroff_panel_button = QtWidgets.QPushButton(self.options_panel)
        self.poweroff_panel_button.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    color: #eaf0ff;\n"
"}\n"
"\n"
"QPushButton[select=\"true\"] {\n"
"    background: #767676;\n"
"}")
        self.poweroff_panel_button.setObjectName("poweroff_panel_button")
        self.verticalLayout_3.addWidget(self.poweroff_panel_button)
        self.restart_po_button = QtWidgets.QPushButton(self.options_panel)
        self.restart_po_button.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    color: #eaf0ff;\n"
"}\n"
"\n"
"QPushButton[select=\"true\"] {\n"
"    background: #767676;\n"
"}")
        self.restart_po_button.setObjectName("restart_po_button")
        self.verticalLayout_3.addWidget(self.restart_po_button)
        self.diagnostic_button = QtWidgets.QPushButton(self.options_panel)
        self.diagnostic_button.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    color: #eaf0ff;\n"
"}\n"
"\n"
"QPushButton[select=\"true\"] {\n"
"    background: #767676;\n"
"}")
        self.diagnostic_button.setObjectName("diagnostic_button")
        self.verticalLayout_3.addWidget(self.diagnostic_button)
        self.close_option_button = QtWidgets.QPushButton(self.options_panel)
        self.close_option_button.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    color: #eaf0ff;\n"
"}\n"
"\n"
"QPushButton[select=\"true\"] {\n"
"    background: #767676;\n"
"}")
        self.close_option_button.setObjectName("close_option_button")
        self.verticalLayout_3.addWidget(self.close_option_button)
        self.horizontalLayout.addWidget(self.options_panel)
        self.diagnostic_container = QtWidgets.QStackedWidget(self.options_container)
        self.diagnostic_container.setObjectName("diagnostic_container")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: transparent;")
        self.page.setObjectName("page")
        self.diagnostic_container.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("background-color: transparent;")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.diagnostic_panel = QtWidgets.QWidget(self.page_2)
        self.diagnostic_panel.setStyleSheet("QWidget {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 128);\n"
"}")
        self.diagnostic_panel.setObjectName("diagnostic_panel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.diagnostic_panel)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.diagnostic_panel)
        self.label_2.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #eaf0ff;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.diagnostic_text = QtWidgets.QPlainTextEdit(self.diagnostic_panel)
        self.diagnostic_text.setStyleSheet("QPlainTextEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #eaf0ff;\n"
"}")
        self.diagnostic_text.setObjectName("diagnostic_text")
        self.verticalLayout_11.addWidget(self.diagnostic_text)
        self.verticalLayout_6.addWidget(self.diagnostic_panel)
        self.diagnostic_container.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.diagnostic_container)
        self.horizontalLayout_6.addWidget(self.options_container)
        self.verticalLayout.addWidget(self.up_container)
        self.down_container = QtWidgets.QWidget(self.container)
        self.down_container.setObjectName("down_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.down_container)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.weather_container = QtWidgets.QStackedWidget(self.down_container)
        self.weather_container.setStyleSheet("")
        self.weather_container.setObjectName("weather_container")
        self.update_weather = QtWidgets.QWidget()
        self.update_weather.setStyleSheet("#update_weather {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 128);\n"
"}")
        self.update_weather.setObjectName("update_weather")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.update_weather)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.update_weather_label = QtWidgets.QLabel(self.update_weather)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_weather_label.setFont(font)
        self.update_weather_label.setStyleSheet("color: #eaf0ff;")
        self.update_weather_label.setAlignment(QtCore.Qt.AlignCenter)
        self.update_weather_label.setObjectName("update_weather_label")
        self.verticalLayout_8.addWidget(self.update_weather_label)
        self.weather_container.addWidget(self.update_weather)
        self.show_weather = QtWidgets.QWidget()
        self.show_weather.setStyleSheet("#show_weather {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 128);\n"
"}")
        self.show_weather.setObjectName("show_weather")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.show_weather)
        self.verticalLayout_7.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.show_weather)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.weather_img = QtWidgets.QLabel(self.widget)
        self.weather_img.setStyleSheet("QLabel {\n"
"    color: #eaf0ff;\n"
"}")
        self.weather_img.setObjectName("weather_img")
        self.horizontalLayout_4.addWidget(self.weather_img)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.weather_text_1 = QtWidgets.QLabel(self.widget_4)
        self.weather_text_1.setStyleSheet("color: #eaf0ff;")
        self.weather_text_1.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_text_1.setObjectName("weather_text_1")
        self.verticalLayout_4.addWidget(self.weather_text_1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.weather_text_2 = QtWidgets.QLabel(self.widget_5)
        self.weather_text_2.setStyleSheet("color: #eaf0ff;")
        self.weather_text_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weather_text_2.setObjectName("weather_text_2")
        self.horizontalLayout_5.addWidget(self.weather_text_2)
        self.weather_text_3 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.weather_text_3.setFont(font)
        self.weather_text_3.setStyleSheet("color: #b52b2e;")
        self.weather_text_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weather_text_3.setObjectName("weather_text_3")
        self.horizontalLayout_5.addWidget(self.weather_text_3)
        self.weather_text_4 = QtWidgets.QLabel(self.widget_5)
        self.weather_text_4.setStyleSheet("color: #eaf0ff;")
        self.weather_text_4.setObjectName("weather_text_4")
        self.horizontalLayout_5.addWidget(self.weather_text_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_4.addWidget(self.widget_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_7.addWidget(self.widget)
        self.weather_time_update_text = QtWidgets.QLabel(self.show_weather)
        self.weather_time_update_text.setStyleSheet("color: #eaf0ff;")
        self.weather_time_update_text.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_time_update_text.setObjectName("weather_time_update_text")
        self.verticalLayout_7.addWidget(self.weather_time_update_text)
        self.weather_container.addWidget(self.show_weather)
        self.horizontalLayout_3.addWidget(self.weather_container)
        self.home_info_container = QtWidgets.QStackedWidget(self.down_container)
        self.home_info_container.setMinimumSize(QtCore.QSize(0, 0))
        self.home_info_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.home_info_container.setStyleSheet("")
        self.home_info_container.setObjectName("home_info_container")
        self.update_home_info = QtWidgets.QWidget()
        self.update_home_info.setStyleSheet("#update_home_info {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 128);\n"
"}")
        self.update_home_info.setObjectName("update_home_info")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.update_home_info)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.update_home_info_label = QtWidgets.QLabel(self.update_home_info)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_home_info_label.setFont(font)
        self.update_home_info_label.setStyleSheet("color: #eaf0ff;")
        self.update_home_info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.update_home_info_label.setObjectName("update_home_info_label")
        self.verticalLayout_9.addWidget(self.update_home_info_label)
        self.home_info_container.addWidget(self.update_home_info)
        self.show_home_info = QtWidgets.QWidget()
        self.show_home_info.setStyleSheet("#show_home_info {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 128);\n"
"}")
        self.show_home_info.setObjectName("show_home_info")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.show_home_info)
        self.verticalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.home_info_label = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_info_label.sizePolicy().hasHeightForWidth())
        self.home_info_label.setSizePolicy(sizePolicy)
        self.home_info_label.setMinimumSize(QtCore.QSize(0, 16))
        self.home_info_label.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.home_info_label.setFont(font)
        self.home_info_label.setStyleSheet("QLabel {\n"
"    color: #eaf0ff;\n"
"}")
        self.home_info_label.setObjectName("home_info_label")
        self.verticalLayout_10.addWidget(self.home_info_label)
        self.pressure_label = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_label.sizePolicy().hasHeightForWidth())
        self.pressure_label.setSizePolicy(sizePolicy)
        self.pressure_label.setMinimumSize(QtCore.QSize(0, 16))
        self.pressure_label.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pressure_label.setFont(font)
        self.pressure_label.setStyleSheet("QLabel {\n"
"    color: #607594;\n"
"}")
        self.pressure_label.setObjectName("pressure_label")
        self.verticalLayout_10.addWidget(self.pressure_label)
        self.pressure_value = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_value.sizePolicy().hasHeightForWidth())
        self.pressure_value.setSizePolicy(sizePolicy)
        self.pressure_value.setMinimumSize(QtCore.QSize(0, 16))
        self.pressure_value.setMaximumSize(QtCore.QSize(16777215, 16))
        self.pressure_value.setStyleSheet("QLabel {\n"
"    color: #eaf0ff;\n"
"}")
        self.pressure_value.setObjectName("pressure_value")
        self.verticalLayout_10.addWidget(self.pressure_value)
        self.temperature_label = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperature_label.sizePolicy().hasHeightForWidth())
        self.temperature_label.setSizePolicy(sizePolicy)
        self.temperature_label.setMinimumSize(QtCore.QSize(0, 16))
        self.temperature_label.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.temperature_label.setFont(font)
        self.temperature_label.setStyleSheet("QLabel {\n"
"    color: #607594;\n"
"}")
        self.temperature_label.setObjectName("temperature_label")
        self.verticalLayout_10.addWidget(self.temperature_label)
        self.temperature_value = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperature_value.sizePolicy().hasHeightForWidth())
        self.temperature_value.setSizePolicy(sizePolicy)
        self.temperature_value.setMinimumSize(QtCore.QSize(0, 16))
        self.temperature_value.setMaximumSize(QtCore.QSize(16777215, 16))
        self.temperature_value.setStyleSheet("QLabel {\n"
"    color: #eaf0ff;\n"
"}")
        self.temperature_value.setObjectName("temperature_value")
        self.verticalLayout_10.addWidget(self.temperature_value)
        self.humidity_label = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidity_label.sizePolicy().hasHeightForWidth())
        self.humidity_label.setSizePolicy(sizePolicy)
        self.humidity_label.setMinimumSize(QtCore.QSize(0, 16))
        self.humidity_label.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.humidity_label.setFont(font)
        self.humidity_label.setStyleSheet("QLabel {\n"
"    color: #607594;\n"
"}")
        self.humidity_label.setObjectName("humidity_label")
        self.verticalLayout_10.addWidget(self.humidity_label)
        self.humidity_value = QtWidgets.QLabel(self.show_home_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidity_value.sizePolicy().hasHeightForWidth())
        self.humidity_value.setSizePolicy(sizePolicy)
        self.humidity_value.setMinimumSize(QtCore.QSize(0, 16))
        self.humidity_value.setMaximumSize(QtCore.QSize(16777215, 16))
        self.humidity_value.setStyleSheet("QLabel {\n"
"    color: #eaf0ff;\n"
"}")
        self.humidity_value.setObjectName("humidity_value")
        self.verticalLayout_10.addWidget(self.humidity_value)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem7)
        self.home_info_container.addWidget(self.show_home_info)
        self.horizontalLayout_3.addWidget(self.home_info_container)
        self.verticalLayout.addWidget(self.down_container)
        self.debug_container = QtWidgets.QWidget(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debug_container.sizePolicy().hasHeightForWidth())
        self.debug_container.setSizePolicy(sizePolicy)
        self.debug_container.setStyleSheet("#debug_container {\n"
"    border: 1px solid #30363d;\n"
"    border-radius: 8px;\n"
"    background-color: rgba(22, 27, 34, 160);\n"
"}")
        self.debug_container.setObjectName("debug_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.debug_container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.debug_widget = QtWidgets.QLabel(self.debug_container)
        self.debug_widget.setStyleSheet("QLabel {\n"
"    color: #eaf0ff;\n"
"}")
        self.debug_widget.setObjectName("debug_widget")
        self.horizontalLayout_2.addWidget(self.debug_widget)
        self.verticalLayout.addWidget(self.debug_container)
        self.verticalLayout_5.addWidget(self.container)
        self.verticalLayout_2.addWidget(self.black_container)

        self.retranslateUi(Form)
        self.diagnostic_container.setCurrentIndex(1)
        self.weather_container.setCurrentIndex(0)
        self.home_info_container.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "INFOPANEL"))
        self.date_widget.setText(_translate("Form", "DATE"))
        self.time_widget.setText(_translate("Form", "TIME"))
        self.label.setText(_translate("Form", "Функции"))
        self.restart_panel_button.setText(_translate("Form", "Перезапуск панели"))
        self.poweroff_panel_button.setText(_translate("Form", "Выключение панели"))
        self.restart_po_button.setText(_translate("Form", "Перезапуск ПО"))
        self.diagnostic_button.setText(_translate("Form", "Диагностика"))
        self.close_option_button.setText(_translate("Form", "Закрыть функции"))
        self.label_2.setText(_translate("Form", "Диагностика"))
        self.update_weather_label.setText(_translate("Form", "Погода\n"
"обновляется"))
        self.weather_img.setText(_translate("Form", "WEATHER_IMG"))
        self.weather_text_1.setText(_translate("Form", "WEATHER_TEXT_1"))
        self.weather_text_2.setText(_translate("Form", "W1"))
        self.weather_text_3.setText(_translate("Form", "W2"))
        self.weather_text_4.setText(_translate("Form", "W3"))
        self.weather_time_update_text.setText(_translate("Form", "WEATHER_TIME"))
        self.update_home_info_label.setText(_translate("Form", "Данные\n"
"обновляются"))
        self.home_info_label.setText(_translate("Form", "Квартира"))
        self.pressure_label.setText(_translate("Form", "Давление"))
        self.pressure_value.setText(_translate("Form", "PRESSURE"))
        self.temperature_label.setText(_translate("Form", "Температура"))
        self.temperature_value.setText(_translate("Form", "TEMPERATURE"))
        self.humidity_label.setText(_translate("Form", "Влажность"))
        self.humidity_value.setText(_translate("Form", "HUMIDITY"))
        self.debug_widget.setText(_translate("Form", "WEATHER_TEXT"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
