#!/bin/python3

import time
import ads_1x15
import wiringpi
from wiringpi import GPIO, HIGH, LOW

ADS = ads_1x15.ADS1115(1, 0x48)

# set gain to 4.096V max
ADS.setGain(ADS.PGA_6_144V)
convert_volt = ADS.toVoltage()

while True:
    wiringpi.wiringPiSetup()
    wiringpi.pinMode(15, GPIO.OUTPUT)
    wiringpi.digitalWrite(15, LOW)

    val_0 = ADS.readADC(0)
    val_1 = ADS.readADC(1)
    val_2 = ADS.readADC(2)

    wiringpi.digitalWrite(15, HIGH)
    time.sleep(0.280)
    val_3 = ADS.readADC(3)
    time.sleep(0.40)
    wiringpi.digitalWrite(15, LOW)

    print("Analog0: {0:d}\t{1:.3f} V".format(val_0, val_0 * convert_volt))
    print("Analog1: {0:d}\t{1:.3f} V".format(val_1, val_1 * convert_volt))
    print("Analog2: {0:d}\t{1:.3f} V".format(val_2, val_2 * convert_volt))
    print("Analog3: {0:d}\t{1:.3f} V".format(val_3, val_3 * convert_volt))

    print("0.17 * val_3(%s) * self.convert_volt(%s) - 0.1" % (val_3, convert_volt))
    dust3 = 0.17 * val_3 * convert_volt - 0.1
    print("Dust3: {0:d}\t{1:.3f} V".format(val_3, dust3))

    time.sleep(1)
